apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubeblocks-addons
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/staging/kubeblocks/addons
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 15m0s
  dependsOn:
    - name: kubeblocks

