apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubeblocks
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/staging/kubeblocks
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 10m0s
